#!/usr/bin/env python3
"""Update tour + help playback/settings strings in all locale JSON files."""
import json
import os

DIR = os.path.join(
    os.path.dirname(__file__), "..", "src", "WhereWindsMeetMidiPlayer", "Assets", "Localization"
)

# English source strings
EN = {
    "Tour_01_Title": "Welcome!",
    "Tour_01_Desc": "Short tour for playing MIDI in Where Winds Meet. Next continues, Back goes back, Skip ends the tour. You can switch Sakura (pink) or Wuxia (dark) theme anytime in Settings.",
    "Tour_02_Title": "Left menu",
    "Tour_02_Desc": "Library = your MIDI files. Catalogue = community songs. Favorites, History, and Settings are below. Tap a row to open it. The playlist column stays on screen beside Library, Catalogue, Favorites, and History.",
    "Tour_03_Title": "Top buttons",
    "Tour_03_Desc": "Patreon shows supporter perks. Discord opens our server. ? runs this tour again. Update appears when a newer version is ready. Minimize or close Debra — playback can continue while keys are sent to the game.",
    "Tour_04_Title": "Your library",
    "Tour_04_Desc": "Import or drag .mid / .midi files (or folders) here. Search finds songs quickly. Double-click or ▶ to play. Clear only empties the list — your files on disk are not deleted.",
    "Tour_05_Title": "Community catalogue",
    "Tour_05_Desc": "Songs from the community (needs discord-catalogue.json next to the app). Refresh updates the list. Search and Style filter results. Play, double-click, or drag a row to Favorites to like it.",
    "Tour_06_Title": "Playlist",
    "Tour_06_Desc": "Build a set list in the middle column: type a name, + to create, Save / Open / Rename / Delete for saved lists. Add inserts a library song. ▲ ▼ reorder. Drag songs from Library or Catalogue into the list.",
    "Tour_07_Title": "Favorites",
    "Tour_07_Desc": "Songs you liked. Double-click to play. Drag here from Library or Catalogue. The ♥ on the player bar likes the song that is playing now.",
    "Tour_08_Title": "History",
    "Tour_08_Desc": "Recently played songs. Double-click or ▶ to play again. Clear only clears this list. Previous and Next on the player bar move through the list you are viewing.",
    "Tour_09_Title": "Now playing",
    "Tour_09_Desc": "Shows the current song: title, length, note count, and playable range. The picture matches your theme (cherry blossoms or gold ink style).",
    "Tour_10_Title": "Player bar",
    "Tour_10_Desc": "Shuffle, previous, play/pause, stop, next, repeat, auto-play next (▶▶), and favorite (♥). F3–F6 work in-game. Click the progress bar to jump in the song. Volume changes PC sound (game audio too). ⌨ opens the key editor. Below: Smart Transpose, octave ±, track, layout, and language.",
    "Tour_14_Title": "More & see-through",
    "Tour_14_Desc": "Tap More on the player bar. Fade makes the whole window transparent so you can see the game behind Debra — useful when the app sits on top of the game. Mapping chooses how notes are played. Note ms, Chord ms, and Mod ms fix timing if something sounds wrong.",
    "Tour_11_Title": "Settings",
    "Tour_11_Desc": "Theme (Sakura or Wuxia), game path, test keys, and player hotkeys (F3–F6). Advanced settings: note mapping, small timing tweaks, and help for 21-key vs 36-key in the game. Auto-play next sets the pause before the next song.",
    "Tour_12_Title": "Quick tips",
    "Tour_12_Desc": "Open instrument mode in the game before playing. Keep DebraMidiPlayer.exe, Assets, and discord-catalogue.json in the same folder. Administrator mode often helps keys reach the game. Wrong notes? Try Smart Transpose and match your key layout (press F1 in-game for 36-key mode).",
    "Tour_13_Title": "Help again",
    "Tour_13_Desc": "Press ? anytime to replay this tour. On the last step, Full guide opens the complete manual with troubleshooting. Have fun playing!",
    "Help_S03_P4": "Update — appears when a newer portable build is available.",
    "Help_S10_P0": "Main buttons: shuffle, previous, play/pause, stop, next, repeat, auto-play next (▶▶), and favorite (♥).",
    "Help_S10_P1": "The bar shows progress — click it to jump in the song. Volume changes Windows master volume (game audio too).",
    "Help_S10_P2": "Bottom row: Smart Transpose fits notes to the game; octave ± shifts the song; Track picks one MIDI part; Layout and Language change keys and text.",
    "Help_S10_P3": "Tap More for mapping, Fade (see-through window over the game), and millisecond tweaks (Note / Chord / Mod ms). ⌨ opens the key layout editor.",
    "Help_S11_P4": "Smart Transpose — shifts MIDI into the playable range.",
    "Help_S11_P5": "Auto-play next — wait time in seconds before the next song.",
    "Help_S11_P6": "Key layout — must match the game (e.g. Debra 36 Keys). Edit visually or open the keymaps folder.",
    "Help_S11_P7": "Advanced settings — note mapping mode, note/chord/modifier delays, and tips for 21-key vs 36-key Free Play in the game.",
}

LANG = {
    "fr": {
        "Tour_01_Title": "Bienvenue !",
        "Tour_01_Desc": "Petit tour pour jouer des MIDI dans Where Winds Meet. Suivant continue, Retour revient en arrière, Ignorer ferme le tour. Thème Sakura (rose) ou Wuxia (sombre) dans Paramètres.",
        "Tour_02_Title": "Menu gauche",
        "Tour_02_Desc": "Bibliothèque = vos fichiers MIDI. Catalogue = morceaux de la communauté. Favoris, Historique et Paramètres en dessous. Cliquez une ligne pour l’ouvrir. La playlist reste visible à droite.",
        "Tour_03_Title": "Boutons du haut",
        "Tour_03_Desc": "Patreon = avantages supporters. Discord = notre serveur. ? relance ce tour. Mise à jour quand une nouvelle version est prête. Réduire ou fermer Debra — la lecture peut continuer pendant le jeu.",
        "Tour_04_Title": "Votre bibliothèque",
        "Tour_04_Desc": "Importez ou glissez des .mid / .midi (ou dossiers) ici. La recherche filtre vite. Double-clic ou ▶ pour jouer. Vider ne retire que la liste — vos fichiers sur le disque restent.",
        "Tour_05_Title": "Catalogue communauté",
        "Tour_05_Desc": "Morceaux partagés (fichier discord-catalogue.json requis). Actualiser met à jour la liste. Recherche et Style filtrent. Jouer, double-clic, ou glisser vers Favoris pour aimer.",
        "Tour_06_Title": "Playlist",
        "Tour_06_Desc": "Liste au centre : nom, + pour créer, Enregistrer / Ouvrir / Renommer / Supprimer. Ajouter insère un morceau. ▲ ▼ réordonnent. Glissez depuis Bibliothèque ou Catalogue.",
        "Tour_07_Title": "Favoris",
        "Tour_07_Desc": "Morceaux que vous aimez. Double-clic pour jouer. Glissez depuis Bibliothèque ou Catalogue. ♥ sur le lecteur aime le morceau en cours.",
        "Tour_08_Title": "Historique",
        "Tour_08_Desc": "Morceaux récents. Double-clic ou ▶ pour rejouer. Vider efface seulement cette liste. Précédent et Suivant sur le lecteur parcourent la liste active.",
        "Tour_09_Title": "Lecture en cours",
        "Tour_09_Desc": "Titre, durée, nombre de notes et plage jouable. L’illustration suit votre thème (fleurs ou style encre dorée).",
        "Tour_10_Title": "Barre du lecteur",
        "Tour_10_Desc": "Aléatoire, précédent, lecture/pause, stop, suivant, répéter, lecture auto (▶▶), favori (♥). F3–F6 en jeu. Cliquez la barre de progression pour sauter. Volume = son PC. ⌨ édite les touches. Ligne du bas : transposition, octave ±, piste, disposition, langue.",
        "Tour_14_Title": "Plus & transparence",
        "Tour_14_Desc": "Plus sur la barre du lecteur. Fade rend la fenêtre transparente pour voir le jeu derrière — idéal en overlay. Mappage = comment les notes sont jouées. Note ms, Accord ms, Mod ms corrigent le timing.",
        "Tour_11_Title": "Paramètres",
        "Tour_11_Desc": "Thème, chemin du jeu, test des touches, raccourcis F3–F6. Paramètres avancés : mappage, petits délais, aide 21 vs 36 touches. Lecture auto = pause avant le morceau suivant.",
        "Tour_12_Title": "Conseils rapides",
        "Tour_12_Desc": "Mode instrument en jeu avant de jouer. Gardez exe + Assets + discord-catalogue.json ensemble. Mode administrateur aide souvent. Notes fausses ? Transposition intelligente + même disposition de touches (F1 → 36 touches en jeu).",
        "Tour_13_Title": "Besoin d’aide ?",
        "Tour_13_Desc": "? relance ce tour. Guide complet sur la dernière étape. Bon jeu !",
        "Help_S03_P4": "Mise à jour — quand une nouvelle version portable est disponible.",
        "Help_S10_P0": "Boutons : aléatoire, précédent, lecture/pause, stop, suivant, répéter, lecture auto (▶▶), favori (♥).",
        "Help_S10_P1": "La barre montre la progression — cliquez pour sauter. Volume = son principal Windows (jeu inclus).",
        "Help_S10_P2": "Ligne du bas : transposition intelligente, octave ±, piste MIDI, disposition et langue.",
        "Help_S10_P3": "Plus : mappage, Fade (fenêtre transparente sur le jeu), délais en ms (Note / Accord / Mod). ⌨ édite les touches.",
        "Help_S11_P4": "Transposition intelligente — adapte les notes à la plage du jeu.",
        "Help_S11_P5": "Lecture auto — temps d’attente en secondes avant le morceau suivant.",
        "Help_S11_P6": "Disposition des touches — doit correspondre au jeu (ex. Debra 36 touches).",
        "Help_S11_P7": "Paramètres avancés — mappage des notes, délais note/accord/modificateur, aide 21 vs 36 touches.",
    },
    "de": {
        "Tour_01_Title": "Willkommen!",
        "Tour_01_Desc": "Kurzer Rundgang für MIDI in Where Winds Meet. Weiter = nächster Schritt, Zurück = zurück, Tour überspringen = beenden. Theme Sakura (rosa) oder Wuxia (dunkel) jederzeit in Einstellungen.",
        "Tour_02_Title": "Linkes Menü",
        "Tour_02_Desc": "Bibliothek = deine MIDI-Dateien. Katalog = Community-Songs. Favoriten, Verlauf, Einstellungen darunter. Zeile antippen zum Öffnen. Die Playlist bleibt rechts sichtbar.",
        "Tour_03_Title": "Obere Buttons",
        "Tour_03_Desc": "Patreon = Supporter-Vorteile. Discord = unser Server. ? = Tour erneut. Update bei neuer Version. Minimieren/Schließen — Wiedergabe kann im Hintergrund weiterlaufen.",
        "Tour_04_Title": "Deine Bibliothek",
        "Tour_04_Desc": "Import oder .mid/.midi (oder Ordner) hierher ziehen. Suche filtert schnell. Doppelklick oder ▶ zum Abspielen. Leeren nur die Liste — Dateien auf der Festplatte bleiben.",
        "Tour_05_Title": "Community-Katalog",
        "Tour_05_Desc": "Geteilte Songs (discord-catalogue.json nötig). Aktualisieren lädt die Liste neu. Suche und Stil filtern. Spielen, Doppelklick oder auf Favoriten ziehen zum Liken.",
        "Tour_06_Title": "Playlist",
        "Tour_06_Desc": "Setliste in der Mitte: Name, + erstellen, Speichern/Öffnen/Umbenennen/Löschen. Hinzufügen aus Bibliothek. ▲ ▼ sortieren. Songs aus Bibliothek oder Katalog ziehen.",
        "Tour_07_Title": "Favoriten",
        "Tour_07_Desc": "Gelikte Songs. Doppelklick zum Spielen. Hierher ziehen aus Bibliothek/Katalog. ♥ in der Player-Leiste liked den aktuellen Song.",
        "Tour_08_Title": "Verlauf",
        "Tour_08_Desc": "Zuletzt gespielt. Doppelklick oder ▶ erneut. Leeren nur diese Liste. Zurück/Weiter in der Leiste durch die aktive Liste.",
        "Tour_09_Title": "Jetzt läuft",
        "Tour_09_Desc": "Titel, Länge, Notenzahl und Spielbereich. Bild passt zum Theme (Kirschblüten oder Gold-Tinte).",
        "Tour_10_Title": "Player-Leiste",
        "Tour_10_Desc": "Shuffle, zurück, play/pause, stop, weiter, repeat, Auto-Weiter (▶▶), Favorit (♥). F3–F6 im Spiel. Fortschrittsbalken anklicken zum Springen. Lautstärke = PC-Sound. ⌨ Tasten-Editor. Unten: Smart Transpose, Oktave ±, Spur, Layout, Sprache.",
        "Tour_14_Title": "Mehr & Durchsicht",
        "Tour_14_Desc": "Mehr in der Player-Leiste. Fade macht das Fenster transparent — Spiel dahinter sichtbar. Mapping = wie Noten gespielt werden. Note ms, Akkord ms, Mod ms für Timing.",
        "Tour_11_Title": "Einstellungen",
        "Tour_11_Desc": "Theme, Spielpfad, Tastentest, Hotkeys F3–F6. Erweitert: Mapping, kleine Timing-Werte, Hilfe 21 vs 36 Tasten. Auto-Weiter = Pause vor nächstem Song.",
        "Tour_12_Title": "Kurz-Tipps",
        "Tour_12_Desc": "Instrumentmodus im Spiel zuerst. exe + Assets + discord-catalogue.json zusammen halten. Admin-Modus hilft oft. Falsche Noten? Smart Transpose + passendes Layout (F1 → 36 Tasten).",
        "Tour_13_Title": "Noch Hilfe?",
        "Tour_13_Desc": "? startet die Tour erneut. Vollständiger Leitfaden am Ende. Viel Spaß!",
        "Help_S03_P4": "Update — wenn eine neuere Portable-Version verfügbar ist.",
        "Help_S10_P0": "Buttons: Shuffle, zurück, play/pause, stop, weiter, repeat, Auto-Weiter (▶▶), Favorit (♥).",
        "Help_S10_P1": "Balken zeigt Fortschritt — klicken zum Springen. Lautstärke = Windows-Gesamtlautstärke.",
        "Help_S10_P2": "Unten: Smart Transpose, Oktave ±, MIDI-Spur, Layout und Sprache.",
        "Help_S10_P3": "Mehr: Mapping, Fade (transparent über dem Spiel), ms-Felder (Note/Akkord/Mod). ⌨ Tasten-Editor.",
        "Help_S11_P4": "Smart Transpose — verschiebt MIDI in den Spielbereich.",
        "Help_S11_P5": "Auto-Weiter — Wartezeit in Sekunden vor dem nächsten Song.",
        "Help_S11_P6": "Tastenlayout — muss zum Spiel passen (z. B. Debra 36 Tasten).",
        "Help_S11_P7": "Erweiterte Einstellungen — Mapping, Note/Akkord/Mod-Verzögerung, Hilfe 21 vs 36 Tasten.",
    },
    "es": {
        "Tour_01_Title": "¡Bienvenido!",
        "Tour_01_Desc": "Tour rápido para MIDI en Where Winds Meet. Siguiente continúa, Atrás vuelve, Omitir cierra. Tema Sakura (rosa) o Wuxia (oscuro) en Ajustes.",
        "Tour_02_Title": "Menú izquierdo",
        "Tour_02_Desc": "Biblioteca = tus archivos MIDI. Catálogo = canciones de la comunidad. Favoritos, Historial y Ajustes abajo. Pulsa una fila para abrirla. La playlist sigue visible a la derecha.",
        "Tour_03_Title": "Botones superiores",
        "Tour_03_Desc": "Patreon = recompensas. Discord = nuestro servidor. ? repite este tour. Actualizar cuando hay nueva versión. Minimizar o cerrar — la reproducción puede seguir en el juego.",
        "Tour_04_Title": "Tu biblioteca",
        "Tour_04_Desc": "Importa o arrastra .mid / .midi (o carpetas). Buscar filtra rápido. Doble clic o ▶ para reproducir. Vaciar solo limpia la lista — los archivos en disco no se borran.",
        "Tour_05_Title": "Catálogo comunidad",
        "Tour_05_Desc": "Canciones compartidas (necesita discord-catalogue.json). Actualizar renueva la lista. Buscar y Estilo filtran. Reproducir, doble clic o arrastrar a Favoritos.",
        "Tour_06_Title": "Lista de reproducción",
        "Tour_06_Desc": "Lista en el centro: nombre, + crear, Guardar/Abrir/Renombrar/Eliminar. Añadir desde biblioteca. ▲ ▼ reordenan. Arrastra desde Biblioteca o Catálogo.",
        "Tour_07_Title": "Favoritos",
        "Tour_07_Desc": "Canciones que te gustan. Doble clic para reproducir. Arrastra desde Biblioteca o Catálogo. ♥ en el reproductor marca la canción actual.",
        "Tour_08_Title": "Historial",
        "Tour_08_Desc": "Lo reproducido recientemente. Doble clic o ▶ otra vez. Vaciar solo esta lista. Anterior y Siguiente en el reproductor recorren la lista activa.",
        "Tour_09_Title": "Reproduciendo",
        "Tour_09_Desc": "Título, duración, notas y rango. La imagen sigue tu tema (cerezos o estilo dorado).",
        "Tour_10_Title": "Barra del reproductor",
        "Tour_10_Desc": "Aleatorio, anterior, play/pausa, stop, siguiente, repetir, auto (▶▶), favorito (♥). F3–F6 en el juego. Clic en la barra para saltar. Volumen = sonido del PC. ⌨ edita teclas. Abajo: transposición, octava ±, pista, diseño, idioma.",
        "Tour_14_Title": "Más y transparencia",
        "Tour_14_Desc": "Más en la barra. Fade hace la ventana transparente para ver el juego detrás. Mapeo elige cómo se tocan las notas. Note ms, Chord ms y Mod ms corrigen el tiempo.",
        "Tour_11_Title": "Ajustes",
        "Tour_11_Desc": "Tema, ruta del juego, probar teclas, atajos F3–F6. Avanzado: mapeo, pequeños retrasos, ayuda 21 vs 36 teclas. Auto = pausa antes de la siguiente canción.",
        "Tour_12_Title": "Consejos rápidos",
        "Tour_12_Desc": "Modo instrumento en el juego primero. Mantén exe + Assets + discord-catalogue.json juntos. Administrador ayuda. Notas mal? Transposición inteligente + mismo diseño (F1 → 36 teclas).",
        "Tour_13_Title": "¿Más ayuda?",
        "Tour_13_Desc": "? repite el tour. Guía completa en el último paso. ¡Disfruta la música!",
        "Help_S03_P4": "Actualizar — cuando hay una versión portable nueva.",
        "Help_S10_P0": "Botones: aleatorio, anterior, play/pausa, stop, siguiente, repetir, auto (▶▶), favorito (♥).",
        "Help_S10_P1": "La barra muestra el progreso — clic para saltar. Volumen = sonido maestro de Windows.",
        "Help_S10_P2": "Fila inferior: transposición inteligente, octava ±, pista MIDI, diseño e idioma.",
        "Help_S10_P3": "Más: mapeo, Fade (ventana transparente sobre el juego), ms (Nota/Acorde/Mod). ⌨ editor de teclas.",
        "Help_S11_P4": "Transposición inteligente — adapta las notas al juego.",
        "Help_S11_P5": "Auto siguiente — espera en segundos antes de la próxima canción.",
        "Help_S11_P6": "Diseño de teclas — debe coincidir con el juego (ej. Debra 36 teclas).",
        "Help_S11_P7": "Ajustes avanzados — mapeo, retrasos de nota/acorde/modificador, ayuda 21 vs 36 teclas.",
    },
    "it": {
        "Tour_01_Title": "Benvenuto!",
        "Tour_01_Desc": "Tour rapido per MIDI in Where Winds Meet. Avanti continua, Indietro torna, Salta chiude. Tema Sakura (rosa) o Wuxia (scuro) in Impostazioni.",
        "Tour_02_Title": "Menu sinistro",
        "Tour_02_Desc": "Libreria = i tuoi MIDI. Catalogo = brani della community. Preferiti, Cronologia e Impostazioni sotto. Tocca una riga per aprirla. La playlist resta visibile a destra.",
        "Tour_03_Title": "Pulsanti in alto",
        "Tour_03_Desc": "Patreon = vantaggi supporter. Discord = server. ? ripete il tour. Aggiorna quando c’è una nuova versione. Minimizza o chiudi — la riproduzione può continuare col gioco.",
        "Tour_04_Title": "La tua libreria",
        "Tour_04_Desc": "Importa o trascina .mid / .midi (o cartelle). Cerca filtra velocemente. Doppio clic o ▶ per suonare. Svuota solo la lista — i file sul disco restano.",
        "Tour_05_Title": "Catalogo community",
        "Tour_05_Desc": "Brani condivisi (serve discord-catalogue.json). Aggiorna ricarica la lista. Cerca e Stile filtrano. Suona, doppio clic o trascina su Preferiti.",
        "Tour_06_Title": "Playlist",
        "Tour_06_Desc": "Lista al centro: nome, + crea, Salva/Apri/Rinomina/Elimina. Aggiungi dalla libreria. ▲ ▼ riordinano. Trascina da Libreria o Catalogo.",
        "Tour_07_Title": "Preferiti",
        "Tour_07_Desc": "Brani che ti piacciono. Doppio clic per suonare. Trascina da Libreria o Catalogo. ♥ sul player mette like al brano attuale.",
        "Tour_08_Title": "Cronologia",
        "Tour_08_Desc": "Brani recenti. Doppio clic o ▶ di nuovo. Svuota solo questa lista. Precedente e Successivo sul player nella lista attiva.",
        "Tour_09_Title": "In riproduzione",
        "Tour_09_Desc": "Titolo, durata, note e range. L’immagine segue il tema (ciliegio o inchiostro dorato).",
        "Tour_10_Title": "Barra del player",
        "Tour_10_Desc": "Shuffle, precedente, play/pausa, stop, successivo, repeat, auto (▶▶), preferito (♥). F3–F6 nel gioco. Clic sulla barra per saltare. Volume = audio PC. ⌨ modifica tasti. Sotto: trasposizione, ottava ±, traccia, layout, lingua.",
        "Tour_14_Title": "Altro e trasparenza",
        "Tour_14_Desc": "Altro sulla barra. Fade rende trasparente la finestra per vedere il gioco dietro. Mapping sceglie come suonare le note. Note ms, Accord ms, Mod ms per il timing.",
        "Tour_11_Title": "Impostazioni",
        "Tour_11_Desc": "Tema, percorso gioco, test tasti, hotkey F3–F6. Avanzate: mapping, piccoli ritardi, aiuto 21 vs 36 tasti. Auto = pausa prima del brano successivo.",
        "Tour_12_Title": "Suggerimenti",
        "Tour_12_Desc": "Modalità strumento nel gioco prima. Tenere exe + Assets + discord-catalogue.json insieme. Admin aiuta. Note sbagliate? Trasposizione smart + layout corretto (F1 → 36 tasti).",
        "Tour_13_Title": "Serve ancora aiuto?",
        "Tour_13_Desc": "? ripete il tour. Guida completa all’ultimo passo. Buon divertimento!",
        "Help_S03_P4": "Aggiorna — quando è disponibile una nuova build portable.",
        "Help_S10_P0": "Pulsanti: shuffle, precedente, play/pausa, stop, successivo, repeat, auto (▶▶), preferito (♥).",
        "Help_S10_P1": "La barra mostra il progresso — clic per saltare. Volume = volume master Windows.",
        "Help_S10_P2": "Riga inferiore: trasposizione smart, ottava ±, traccia MIDI, layout e lingua.",
        "Help_S10_P3": "Altro: mapping, Fade (finestra trasparente sul gioco), ms (Nota/Accordo/Mod). ⌨ editor tasti.",
        "Help_S11_P4": "Trasposizione smart — adatta le note al gioco.",
        "Help_S11_P5": "Auto successivo — attesa in secondi prima del brano successivo.",
        "Help_S11_P6": "Layout tasti — deve corrispondere al gioco (es. Debra 36 tasti).",
        "Help_S11_P7": "Impostazioni avanzate — mapping, ritardi nota/accordo/modificatore, aiuto 21 vs 36 tasti.",
    },
    "pt": {
        "Tour_01_Title": "Bem-vindo!",
        "Tour_01_Desc": "Tour rápido para MIDI em Where Winds Meet. Próximo continua, Voltar retorna, Ignorar fecha. Tema Sakura (rosa) ou Wuxia (escuro) em Configurações.",
        "Tour_02_Title": "Menu esquerdo",
        "Tour_02_Desc": "Biblioteca = seus MIDIs. Catálogo = músicas da comunidade. Favoritos, Histórico e Configurações abaixo. Toque uma linha para abrir. A playlist fica visível à direita.",
        "Tour_03_Title": "Botões superiores",
        "Tour_03_Desc": "Patreon = recompensas. Discord = servidor. ? repete o tour. Atualizar quando há versão nova. Minimizar ou fechar — a reprodução pode continuar no jogo.",
        "Tour_04_Title": "Sua biblioteca",
        "Tour_04_Desc": "Importe ou arraste .mid / .midi (ou pastas). Busca filtra rápido. Duplo clique ou ▶ para tocar. Limpar só esvazia a lista — arquivos no disco ficam.",
        "Tour_05_Title": "Catálogo comunidade",
        "Tour_05_Desc": "Músicas compartilhadas (precisa discord-catalogue.json). Atualizar renova a lista. Busca e Estilo filtram. Tocar, duplo clique ou arrastar a Favoritos.",
        "Tour_06_Title": "Playlist",
        "Tour_06_Desc": "Lista no centro: nome, + criar, Salvar/Abrir/Renomear/Eliminar. Adicionar da biblioteca. ▲ ▼ reordenam. Arraste da Biblioteca ou Catálogo.",
        "Tour_07_Title": "Favoritos",
        "Tour_07_Desc": "Músicas curtidas. Duplo clique para tocar. Arraste da Biblioteca ou Catálogo. ♥ no player curte a faixa atual.",
        "Tour_08_Title": "Histórico",
        "Tour_08_Desc": "Reproduções recentes. Duplo clique ou ▶ de novo. Limpar só esta lista. Anterior e Próximo no player na lista ativa.",
        "Tour_09_Title": "Tocando agora",
        "Tour_09_Desc": "Título, duração, notas e alcance. A arte segue o tema (cerejeira ou dourado).",
        "Tour_10_Title": "Barra do player",
        "Tour_10_Desc": "Aleatório, anterior, play/pausa, stop, próximo, repetir, auto (▶▶), favorito (♥). F3–F6 no jogo. Clique na barra para pular. Volume = som do PC. ⌨ edita teclas. Abaixo: transposição, oitava ±, faixa, layout, idioma.",
        "Tour_14_Title": "Mais e transparência",
        "Tour_14_Desc": "Mais na barra. Fade torna a janela transparente para ver o jogo atrás. Mapeamento escolhe como as notas são tocadas. Note ms, Chord ms e Mod ms ajustam o tempo.",
        "Tour_11_Title": "Configurações",
        "Tour_11_Desc": "Tema, caminho do jogo, testar teclas, atalhos F3–F6. Avançado: mapeamento, pequenos atrasos, ajuda 21 vs 36 teclas. Auto = pausa antes da próxima faixa.",
        "Tour_12_Title": "Dicas rápidas",
        "Tour_12_Desc": "Modo instrumento no jogo primeiro. Mantenha exe + Assets + discord-catalogue.json juntos. Admin ajuda. Notas erradas? Transposição inteligente + layout certo (F1 → 36 teclas).",
        "Tour_13_Title": "Precisa de ajuda?",
        "Tour_13_Desc": "? repete o tour. Guia completo no último passo. Divirta-se!",
        "Help_S03_P4": "Atualizar — quando há build portable nova.",
        "Help_S10_P0": "Botões: aleatório, anterior, play/pausa, stop, próximo, repetir, auto (▶▶), favorito (♥).",
        "Help_S10_P1": "A barra mostra o progresso — clique para pular. Volume = volume principal do Windows.",
        "Help_S10_P2": "Linha inferior: transposição inteligente, oitava ±, faixa MIDI, layout e idioma.",
        "Help_S10_P3": "Mais: mapeamento, Fade (janela transparente sobre o jogo), ms (Nota/Acorde/Mod). ⌨ editor de teclas.",
        "Help_S11_P4": "Transposição inteligente — adapta notas ao jogo.",
        "Help_S11_P5": "Auto próximo — espera em segundos antes da faixa seguinte.",
        "Help_S11_P6": "Layout de teclas — deve coincidir com o jogo (ex. Debra 36 teclas).",
        "Help_S11_P7": "Configurações avançadas — mapeamento, atrasos de nota/acorde/modificador, ajuda 21 vs 36 teclas.",
    },
    "zh": {
        "Tour_01_Title": "欢迎！",
        "Tour_01_Desc": "Where Winds Meet MIDI 快速导览。下一步继续，上一步返回，跳过结束。可在设置中切换樱花（粉色）或武侠（深色）主题。",
        "Tour_02_Title": "左侧菜单",
        "Tour_02_Desc": "曲库 = 你的 MIDI 文件。目录 = 社区歌曲。下方还有收藏、历史和设置。点击一行打开。播放列表在右侧保持显示。",
        "Tour_03_Title": "顶部按钮",
        "Tour_03_Desc": "Patreon 支持者福利。Discord 社区。? 重新播放本导览。有新版时显示更新。可最小化或关闭 — 播放可在后台继续向游戏发送按键。",
        "Tour_04_Title": "你的曲库",
        "Tour_04_Desc": "导入或拖入 .mid / .midi（或文件夹）。搜索快速筛选。双击或 ▶ 播放。清空只清除列表 — 磁盘上的文件不会删除。",
        "Tour_05_Title": "社区目录",
        "Tour_05_Desc": "社区共享歌曲（需 discord-catalogue.json）。刷新更新列表。搜索和风格筛选。播放、双击或拖到收藏点赞。",
        "Tour_06_Title": "播放列表",
        "Tour_06_Desc": "中间栏建歌单：输入名称、+ 创建、保存/打开/重命名/删除。添加曲库歌曲。▲ ▼ 排序。从曲库或目录拖入。",
        "Tour_07_Title": "收藏",
        "Tour_07_Desc": "喜欢的歌曲。双击播放。从曲库或目录拖入。播放器上的 ♥ 收藏当前歌曲。",
        "Tour_08_Title": "历史",
        "Tour_08_Desc": "最近播放。双击或 ▶ 再播。清空只清此列表。播放器上的上一首/下一首在当前列表中切换。",
        "Tour_09_Title": "正在播放",
        "Tour_09_Desc": "显示标题、时长、音符数和可演奏范围。插图随主题变化（樱花或金色水墨）。",
        "Tour_10_Title": "播放器栏",
        "Tour_10_Desc": "随机、上一首、播放/暂停、停止、下一首、重复、自动连播 (▶▶)、收藏 (♥)。游戏内 F3–F6。点击进度条跳转。音量调节电脑声音。⌨ 编辑键位。下方：智能移调、八度 ±、音轨、布局、语言。",
        "Tour_14_Title": "更多与透明",
        "Tour_14_Desc": "点播放器上的「更多」。淡化使整个窗口透明，可看到背后的游戏 — 适合叠在游戏上。映射选择如何演奏音符。音符/和弦/修饰 ms 可修正时机。",
        "Tour_11_Title": "设置",
        "Tour_11_Desc": "主题、游戏路径、测试按键、播放器快捷键 F3–F6。高级：音符映射、小延迟、21 与 36 键说明。自动播放 = 下一首前的等待时间。",
        "Tour_12_Title": "小贴士",
        "Tour_12_Desc": "先在游戏中打开乐器模式。exe、Assets、discord-catalogue.json 放在同一文件夹。管理员模式常有帮助。音不对？开智能移调并匹配键位（游戏内 F1 选 36 键）。",
        "Tour_13_Title": "再次需要帮助？",
        "Tour_13_Desc": "按 ? 随时重播导览。最后一步可打开完整手册。祝演奏愉快！",
        "Help_S03_P4": "更新 — 有新便携版时显示。",
        "Help_S10_P0": "按钮：随机、上一首、播放/暂停、停止、下一首、重复、自动连播 (▶▶)、收藏 (♥)。",
        "Help_S10_P1": "进度条显示位置 — 点击跳转。音量调节 Windows 主音量。",
        "Help_S10_P2": "底行：智能移调、八度 ±、MIDI 音轨、布局与语言。",
        "Help_S10_P3": "更多：映射、淡化（窗口透明看游戏）、毫秒设置（音符/和弦/修饰）。⌨ 键位编辑器。",
        "Help_S11_P4": "智能移调 — 将 MIDI 移入可演奏范围。",
        "Help_S11_P5": "自动下一首 — 下一首前的等待秒数。",
        "Help_S11_P6": "键位布局 — 须与游戏一致（如 Debra 36 键）。",
        "Help_S11_P7": "高级设置 — 音符映射、音符/和弦/修饰延迟、21 与 36 键帮助。",
    },
    "ja": {
        "Tour_01_Title": "ようこそ！",
        "Tour_01_Desc": "Where Winds Meet で MIDI を演奏する短いツアー。次へで進み、戻るで戻り、スキップで終了。設定で Sakura（ピンク）または Wuxia（ダーク）テーマを変更できます。",
        "Tour_02_Title": "左メニュー",
        "Tour_02_Desc": "ライブラリ = あなたの MIDI。カタログ = コミュニティ曲。下にお気に入り、履歴、設定。行をクリックで開く。プレイリストは右側に常に表示。",
        "Tour_03_Title": "上部ボタン",
        "Tour_03_Desc": "Patreon = サポーター特典。Discord = サーバー。? でこのツアーを再表示。更新 = 新バージョンあり。最小化・閉じても再生は続けられます。",
        "Tour_04_Title": "ライブラリ",
        "Tour_04_Desc": ".mid / .midi やフォルダをインポートまたはドラッグ。検索で素早く絞り込み。ダブルクリックまたは ▶ で再生。クリアはリストのみ削除 — ファイルは残ります。",
        "Tour_05_Title": "コミュニティカタログ",
        "Tour_05_Desc": "共有曲（discord-catalogue.json が必要）。更新でリスト再取得。検索とスタイルで絞り込み。再生、ダブルクリック、お気に入りへドラッグ。",
        "Tour_06_Title": "プレイリスト",
        "Tour_06_Desc": "中央でセットリスト：名前、+ で作成、保存/開く/名前変更/削除。追加で曲を挿入。▲ ▼ で並べ替え。ライブラリやカタログからドラッグ。",
        "Tour_07_Title": "お気に入り",
        "Tour_07_Desc": "いいねした曲。ダブルクリックで再生。ライブラリ/カタログからドラッグ。プレイヤーの ♥ で現在曲をいいね。",
        "Tour_08_Title": "履歴",
        "Tour_08_Desc": "最近再生した曲。ダブルクリックまたは ▶ で再再生。クリアはこのリストのみ。プレイヤーの前/次でリストを移動。",
        "Tour_09_Title": "再生中",
        "Tour_09_Desc": "タイトル、時間、ノート数、演奏範囲。イラストはテーマに合わせて変化（桜または金の水墨）。",
        "Tour_10_Title": "プレイヤーバー",
        "Tour_10_Desc": "シャッフル、前、再生/一時停止、停止、次、リピート、自動次曲 (▶▶)、お気に入り (♥)。ゲーム内 F3–F6。進行バーをクリックでジャンプ。音量は PC 音量。⌨ キー編集。下段：スマート移調、オクターブ ±、トラック、レイアウト、言語。",
        "Tour_14_Title": "詳細と透明",
        "Tour_14_Desc": "プレイヤーの「詳細」をタップ。フェードでウィンドウが透明になり、背後のゲームが見えます。マッピングでノートの扱いを選択。Note ms / Chord ms / Mod ms でタイミング調整。",
        "Tour_11_Title": "設定",
        "Tour_11_Desc": "テーマ、ゲームパス、キーテスト、ホットキー F3–F6。詳細：ノートマップ、小さな遅延、21/36 キーの説明。自動再生 = 次曲までの待機。",
        "Tour_12_Title": "ヒント",
        "Tour_12_Desc": "先にゲームで楽器モードを開く。exe + Assets + discord-catalogue.json を同じフォルダに。管理者モードが有効な場合も。音がおかしい？スマート移調とレイアウト一致（ゲームで F1 → 36 キー）。",
        "Tour_13_Title": "またヘルプが必要？",
        "Tour_13_Desc": "? でいつでもツアー再表示。最後のステップで完全ガイド。楽しんでください！",
        "Help_S03_P4": "更新 — 新しいポータブル版があるときに表示。",
        "Help_S10_P0": "ボタン：シャッフル、前、再生/一時停止、停止、次、リピート、自動次曲 (▶▶)、お気に入り (♥)。",
        "Help_S10_P1": "バーで進行状況 — クリックでジャンプ。音量は Windows マスター音量。",
        "Help_S10_P2": "下段：スマート移調、オクターブ ±、MIDI トラック、レイアウト、言語。",
        "Help_S10_P3": "詳細：マッピング、フェード（ゲーム上で透明）、ms 設定（ノート/コード/修飾）。⌨ キーレイアウト編集。",
        "Help_S11_P4": "スマート移調 — MIDI を演奏範囲に合わせます。",
        "Help_S11_P5": "自動次曲 — 次の曲までの待機秒数。",
        "Help_S11_P6": "キーレイアウト — ゲームと一致させる（例：Debra 36 キー）。",
        "Help_S11_P7": "詳細設定 — ノートマッピング、ノート/コード/修飾遅延、21/36 キーのヒント。",
    },
    "ar": {
        "Tour_01_Title": "مرحبًا!",
        "Tour_01_Desc": "جولة سريعة لتشغيل MIDI في Where Winds Meet. التالي للمتابعة، رجوع للعودة، تخطي للإنهاء. غيّر tema Sakura (وردي) أو Wuxia (داكن) من الإعدادات.",
        "Tour_02_Title": "القائمة اليسرى",
        "Tour_02_Desc": "المكتبة = ملفات MIDI. الكتالوج = أغاني المجتمع. المفضلة، السجل، الإعدادات بالأسفل. انقر صفًا لفتحه. قائمة التشغيل تبقى على اليمين.",
        "Tour_03_Title": "أزرار الأعلى",
        "Tour_03_Desc": "Patreon مزايا الداعمين. Discord السيرفر. ? يعيد الجولة. التحديث عند توفر إصدار جديد. تصغير أو إغلاق — قد يستمر التشغيل أثناء اللعب.",
        "Tour_04_Title": "مكتبتك",
        "Tour_04_Desc": "استورد أو اسحب .mid / .midi (أو مجلدات). البحث يصفّي بسرعة. نقرتين أو ▶ للتشغيل. المسح يفرغ القائمة فقط — الملفات على القرص تبقى.",
        "Tour_05_Title": "كتالوج المجتمع",
        "Tour_05_Desc": "أغاني مشتركة (يحتاج discord-catalogue.json). تحديث يجلب القائمة. البحث والأسلوب للتصفية. تشغيل، نقرتين، أو اسحب إلى المفضلة.",
        "Tour_06_Title": "قائمة التشغيل",
        "Tour_06_Desc": "قائمة في الوسط: اسم، + إنشاء، حفظ/فتح/إعادة تسمية/حذف. إضافة من المكتبة. ▲ ▼ للترتيب. اسحب من المكتبة أو الكتالوج.",
        "Tour_07_Title": "المفضلة",
        "Tour_07_Desc": "الأغاني التي أعجبتك. نقرتين للتشغيل. اسحب من المكتبة أو الكتالوج. ♥ في المشغّل يضيف الإعجاب للأغنية الحالية.",
        "Tour_08_Title": "السجل",
        "Tour_08_Desc": "ما شُغّل مؤخرًا. نقرتين أو ▶ مرة أخرى. المسح يفرغ هذا السجل فقط. السابق والتالي في المشغّل يتنقلان في القائمة النشطة.",
        "Tour_09_Title": "يُشغَّل الآن",
        "Tour_09_Desc": "العنوان، المدة، عدد النوتات، والمدى. الصورة تتغير مع السمة (زهر الكرز أو ذهب داكن).",
        "Tour_10_Title": "شريط المشغّل",
        "Tour_14_Title": "المزيد والشفافية",
        "Tour_14_Desc": "المزيد في الشريط. Fade يجعل النافذة شفافة لرؤية اللعبة خلفها. التعيين يختار كيف تُعزف النوتات. Note ms و Chord ms و Mod ms لضبط التوقيت.",
        "Tour_10_Desc": "عشوائي، سابق، تشغيل/إيقاف مؤقت، إيقاف، تالي، تكرار، تلقائي (▶▶)، مفضلة (♥). F3–F6 في اللعبة. انقر الشريط للقفز. الصوت = صوت الكمبيوتر. ⌨ تعديل المفاتيح. السطر السفلي: نقل ذكي، أوكتاف ±، مسار، تخطيط، لغة.",
        "Tour_11_Title": "الإعدادات",
        "Tour_11_Desc": "السمة، مسار اللعبة، اختبار المفاتيح، اختصارات F3–F6. متقدم: تعيين النوتات، تأخيرات صغيرة، مساعدة 21 مقابل 36 مفتاح. التلقائي = انتظار قبل الأغنية التالية.",
        "Tour_12_Title": "نصائح سريعة",
        "Tour_12_Desc": "افتح وضع الآلة في اللعبة أولًا. احتفظ ب exe + Assets + discord-catalogue.json معًا. وضع المسؤول يساعد غالبًا. نوتات خاطئة؟ النقل الذكي + تخطيط مطابق (F1 → 36 مفتاح).",
        "Tour_13_Title": "تحتاج مساعدة؟",
        "Tour_13_Desc": "? يعيد الجولة. الدليل الكامل في الخطوة الأخيرة. استمتع باللعب!",
        "Help_S03_P4": "تحديث — عند توفر إصدار portable أحدث.",
        "Help_S10_P0": "الأزرار: عشوائي، سابق، تشغيل/إيقاف، إيقاف، تالي، تكرار، تلقائي (▶▶)، مفضلة (♥).",
        "Help_S10_P1": "الشريط يعرض التقدم — انقر للقفز. الصوت = الصوت الرئيسي لـ Windows.",
        "Help_S10_P2": "السطر السفلي: نقل ذكي، أوكتاف ±، مسار MIDI، تخطيط ولغة.",
        "Help_S10_P3": "المزيد: التعيين، Fade (نافذة شفافة فوق اللعبة)، إعدادات ms (نوتة/وتر/معدّل). ⌨ محرر المفاتيح.",
        "Help_S11_P4": "النقل الذكي — يحوّل MIDI إلى مدى اللعب.",
        "Help_S11_P5": "التلقائي — انتظار بالثواني قبل الأغنية التالية.",
        "Help_S11_P6": "تخطيط المفاتيح — يجب أن يطابق اللعبة (مثل Debra 36 مفتاح).",
        "Help_S11_P7": "إعدادات متقدمة — تعيين النوتات، تأخيرات النوتة/الوتر/المعدّل، مساعدة 21 مقابل 36 مفتاح.",
    },
    "vi": {
        "Tour_01_Title": "Chào mừng!",
        "Tour_01_Desc": "Tour ngắn để phát MIDI trong Where Winds Meet. Tiếp theo = tiếp, Quay lại = lùi, Bỏ qua = kết thúc. Đổi theme Sakura (hồng) hoặc Wuxia (tối) trong Cài đặt.",
        "Tour_02_Title": "Menu trái",
        "Tour_02_Desc": "Thư viện = file MIDI của bạn. Danh mục = bài cộng đồng. Yêu thích, Lịch sử, Cài đặt bên dưới. Nhấp một dòng để mở. Playlist vẫn hiện bên phải.",
        "Tour_03_Title": "Nút trên cùng",
        "Tour_03_Desc": "Patreon = phần thưởng supporter. Discord = server. ? chạy lại tour. Cập nhật khi có bản mới. Thu nhỏ hoặc đóng — phát có thể tiếp tục khi chơi game.",
        "Tour_04_Title": "Thư viện của bạn",
        "Tour_04_Desc": "Nhập hoặc kéo .mid / .midi (hoặc thư mục). Tìm kiếm lọc nhanh. Nhấp đúp hoặc ▶ để phát. Xóa hết chỉ xóa danh sách — file trên ổ đĩa vẫn còn.",
        "Tour_05_Title": "Danh mục cộng đồng",
        "Tour_05_Desc": "Bài được chia sẻ (cần discord-catalogue.json). Làm mới cập nhật danh sách. Tìm và Phong cách lọc. Phát, nhấp đúp, hoặc kéo vào Yêu thích.",
        "Tour_06_Title": "Danh sách phát",
        "Tour_06_Desc": "Danh sách giữa: tên, + tạo, Lưu/Mở/Đổi tên/Xóa. Thêm từ thư viện. ▲ ▼ sắp xếp. Kéo từ Thư viện hoặc Danh mục.",
        "Tour_07_Title": "Yêu thích",
        "Tour_07_Desc": "Bài bạn thích. Nhấp đúp để phát. Kéo từ Thư viện hoặc Danh mục. ♥ trên player thích bài đang phát.",
        "Tour_08_Title": "Lịch sử",
        "Tour_08_Desc": "Bài phát gần đây. Nhấp đúp hoặc ▶ lại. Xóa chỉ xóa danh sách này. Trước/Sau trên player trong danh sách hiện tại.",
        "Tour_09_Title": "Đang phát",
        "Tour_09_Desc": "Tiêu đề, thời lượng, số nốt và dải nốt. Hình ảnh theo theme (hoa anh đào hoặc vàng mực).",
        "Tour_10_Title": "Thanh player",
        "Tour_10_Desc": "Ngẫu nhiên, trước, phát/tạm dừng, dừng, sau, lặp, tự phát (▶▶), yêu thích (♥). F3–F6 trong game. Nhấp thanh tiến trình để nhảy. Volume = âm PC. ⌨ sửa phím. Dưới: chuyển giọng, quãng tám ±, track, layout, ngôn ngữ.",
        "Tour_14_Title": "Thêm & trong suốt",
        "Tour_14_Desc": "Nhấp Thêm trên thanh player. Fade làm cửa sổ trong suốt để thấy game phía sau — hữu ích khi đặt app trên game. Mapping chọn cách phát nốt. Note ms, Chord ms, Mod ms sửa timing.",
        "Tour_11_Title": "Cài đặt",
        "Tour_11_Desc": "Theme, đường dẫn game, thử phím, hotkey F3–F6. Nâng cao: ánh xạ nốt, trễ nhỏ, hướng dẫn 21 vs 36 phím. Tự phát = chờ trước bài tiếp.",
        "Tour_12_Title": "Mẹo nhanh",
        "Tour_12_Desc": "Bật chế độ nhạc cụ trong game trước. Giữ exe + Assets + discord-catalogue.json cùng folder. Chạy admin thường giúp. Nốt sai? Chuyển giọng thông minh + layout khớp (F1 → 36 phím).",
        "Tour_13_Title": "Cần trợ giúp?",
        "Tour_13_Desc": "? chạy lại tour. Hướng dẫn đầy đủ ở bước cuối. Chúc bạn chơi vui!",
        "Help_S03_P4": "Cập nhật — khi có bản portable mới.",
        "Help_S10_P0": "Nút: ngẫu nhiên, trước, phát/tạm dừng, dừng, sau, lặp, tự phát (▶▶), yêu thích (♥).",
        "Help_S10_P1": "Thanh hiện tiến trình — nhấp để nhảy. Volume = âm lượng chính Windows.",
        "Help_S10_P2": "Hàng dưới: chuyển giọng thông minh, quãng tám ±, track MIDI, layout và ngôn ngữ.",
        "Help_S10_P3": "Thêm: mapping, Fade (cửa sổ trong suốt trên game), ms (Nốt/Hợp âm/Sửa). ⌨ sửa layout phím.",
        "Help_S11_P4": "Chuyển giọng thông minh — đưa MIDI vào dải có thể chơi.",
        "Help_S11_P5": "Tự phát tiếp — chờ (giây) trước bài sau.",
        "Help_S11_P6": "Layout phím — phải khớp game (vd. Debra 36 phím).",
        "Help_S11_P7": "Cài đặt nâng cao — ánh xạ nốt, trễ nốt/hợp âm/sửa, hướng dẫn 21 vs 36 phím.",
    },
}


def load_json(path):
    with open(path, encoding="utf-8-sig") as f:
        return json.load(f)


def save_json(path, data, indent):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, ensure_ascii=False, indent=indent)
        f.write("\n")


def main():
    en_path = os.path.join(DIR, "en.json")
    en_data = load_json(en_path)
    en_data.update(EN)
    save_json(en_path, en_data, 4)

  # tour-help-en-extra.json — sync tour/help keys from en
    extra_en_path = os.path.join(DIR, "tour-help-en-extra.json")
    if os.path.exists(extra_en_path):
        extra = load_json(extra_en_path)
        for k, v in EN.items():
            extra[k] = v
        save_json(extra_en_path, extra, 4)

    for lang in ["fr", "de", "es", "it", "pt", "zh", "ja", "ar", "vi"]:
        path = os.path.join(DIR, f"{lang}.json")
        data = load_json(path)
        updates = LANG.get(lang, {})
        for k, v in EN.items():
            data[k] = updates.get(k, EN[k])
        indent = 4 if lang == "vi" else 2
        save_json(path, data, indent)

        extra_path = os.path.join(DIR, f"tour-help-{lang}-extra.json")
        if os.path.exists(extra_path):
            extra = load_json(extra_path)
            for k, v in EN.items():
                extra[k] = updates.get(k, EN[k])
            save_json(extra_path, extra, indent)

        print(f"Updated {lang}")

    print("Done.")


if __name__ == "__main__":
    main()
