<Project Sdk="Microsoft.NET.Sdk">



  <PropertyGroup>

    <OutputType>WinExe</OutputType>
    <AssemblyName>DebraMidiPlayer</AssemblyName>
    <Version>1.2.2</Version>
    <AssemblyVersion>1.2.2.0</AssemblyVersion>
    <FileVersion>1.2.2.0</FileVersion>

    <TargetFramework>net8.0-windows</TargetFramework>

    <Nullable>enable</Nullable>

    <ImplicitUsings>enable</ImplicitUsings>

    <UseWPF>true</UseWPF>

    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>debra-app-icon.ico</ApplicationIcon>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>

  </PropertyGroup>



  <ItemGroup>

    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />

    <PackageReference Include="H.Formatters.Newtonsoft.Json" Version="15.0.0" />

    <PackageReference Include="H.Pipes" Version="15.0.0" />

    <PackageReference Include="H.Pipes.AccessControl" Version="15.0.0" />

    <PackageReference Include="Melanchall.DryWetMidi" Version="8.0.3" />

    <PackageReference Include="MeltySynth" Version="2.4.1" />

    <PackageReference Include="NAudio" Version="2.2.1" />

  </ItemGroup>



  <ItemGroup>

    <Resource Include="debra-app-icon.ico" />

    <Content Include="Assets\**\*" CopyToOutputDirectory="PreserveNewest">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>

  </ItemGroup>




</Project>


